name = "LinearInterpolators"
uuid = "2fc109c4-9d77-11e9-32ff-e5c650334c16"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.1.0"

[deps]
ArrayTools = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
InterpolationKernels = "16730964-a2ec-11e9-36fa-47a4f82bfac6"
LazyAlgebra = "aeaa251e-9d76-11e9-311b-83636bf44738"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TwoDimensional = "1907e7ba-7586-4310-a2ba-dd01462aeb50"

[compat]
julia = "1.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Statistics"]
